#!/usr/sbin/nft -f

flush ruleset

table inet pandora {

    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback sempre accettato
        iifname "lo" accept

        # Connessioni già stabilite
        ct state established,related accept

        # Pacchetti non validi scartati
        ct state invalid drop

        # ICMP (ping e diagnostica)
        meta l4proto icmp accept
        meta l4proto ipv6-icmp accept

        # SSH
        tcp dport 22 accept

        # DHCP client (wicked)
        udp dport 68 accept
    }

    chain forward {
        type filter hook forward priority filter; policy accept;

        # Traffico bridge VM — tutto permesso nella LAN
        iifname "br0" accept
        oifname "br0" accept

        # Connessioni stabilite
        ct state established,related accept
        ct state invalid drop
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
